import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Anthony Cueva | Professional Experience, Education & More.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-144 mx-auto py-2">
        <div className="flex flex-col space-y-6 mt-8">projects</div>
      </main>
    </>
  );
}
